/**
 * Seed data: sample vendors with real (approximate) coordinates so
 * haversine matching produces realistic distances. Coordinates are
 * centroid approximations, not survey-grade GPS. The first 8 are the
 * original central-Nairobi set from the phase-1 demo; the rest cover the
 * wider Nairobi Metropolitan Area (Kiambu/Kajiado/Machakos satellite
 * towns) added alongside the expanded coverage in src/neighborhoods.js —
 * without these, a request from Thika or Machakos would only ever find a
 * vendor 30-40km away in central Nairobi, which is correct but a weak demo.
 */
exports.seed = async function (knex) {
  // Clear in FK-safe order.
  await knex('vendor_services').del();
  await knex('jobs').del();
  await knex('vendors').del();
  await knex('users').del();

  const vendors = [
    {
      name: 'James Mwangi',
      business_name: 'Mwangi Auto Rescue',
      vehicle_type: 'Tow Truck',
      phone: '+254712000001',
      rating: 4.9,
      lat: -1.2673,
      lng: 36.8065,
      neighborhood: 'Westlands',
      plate: 'KDD 214J',
      icon: '🚛',
      approval_status: 'approved',
      id_number: '23456781',
      services: ['towing', 'accident', 'engine'],
    },
    {
      name: 'Peter Otieno',
      business_name: 'Otieno Towing Services',
      vehicle_type: 'Flatbed Tow Truck',
      phone: '+254712000002',
      rating: 4.7,
      lat: -1.2921,
      lng: 36.7820,
      neighborhood: 'Kilimani',
      plate: 'KCX 552B',
      icon: '🚛',
      approval_status: 'approved',
      id_number: '24567892',
      services: ['towing', 'accident'],
    },
    {
      name: 'Grace Wanjiru',
      business_name: 'QuickFix Tire & Auto',
      vehicle_type: 'Service Van',
      phone: '+254712000003',
      rating: 4.8,
      lat: -1.2864,
      lng: 36.8172,
      neighborhood: 'CBD',
      plate: 'KDA 887M',
      icon: '🔧',
      approval_status: 'approved',
      id_number: '25678903',
      services: ['tire', 'battery', 'fuel', 'other'],
    },
    {
      name: 'Samuel Kamau',
      business_name: 'Kamau Motors Rescue',
      vehicle_type: 'Pickup + Tools',
      phone: '+254712000004',
      rating: 4.6,
      lat: -1.2793,
      lng: 36.7690,
      neighborhood: 'Lavington',
      plate: 'KBZ 331T',
      icon: '🔧',
      approval_status: 'approved',
      id_number: '26789014',
      services: ['engine', 'battery', 'tire', 'other'],
    },
    {
      name: 'Fatuma Hassan',
      business_name: 'Hassan Roadside Solutions',
      vehicle_type: 'Response Motorbike',
      phone: '+254712000005',
      rating: 4.9,
      lat: -1.2611,
      lng: 36.8172,
      neighborhood: 'Parklands',
      plate: 'KDF 552P',
      icon: '🏍️',
      approval_status: 'approved',
      id_number: '27890125',
      services: ['tire', 'battery', 'fuel'],
    },
    {
      name: 'David Kiprotich',
      business_name: 'Kip Auto Repair',
      vehicle_type: 'Service Van',
      phone: '+254712000006',
      rating: 4.5,
      lat: -1.3194,
      lng: 36.7085,
      neighborhood: 'Karen',
      plate: 'KDG 774R',
      icon: '🔧',
      approval_status: 'approved',
      id_number: '28901236',
      services: ['engine', 'tire', 'other'],
    },
    {
      name: 'Daniel Ngige',
      business_name: 'Ngige Emergency Towing',
      vehicle_type: 'Tow Truck',
      phone: '+254712000007',
      rating: 4.8,
      lat: -1.2963,
      lng: 36.8172,
      neighborhood: 'Upperhill',
      plate: 'KDJ 190N',
      icon: '🚛',
      approval_status: 'approved',
      id_number: '29012347',
      services: ['towing', 'accident'],
    },
    {
      name: 'Mary Njeri',
      business_name: 'South B Rapid Response',
      vehicle_type: 'Service Van',
      phone: '+254712000008',
      rating: 4.7,
      lat: -1.3167,
      lng: 36.8283,
      neighborhood: 'South B',
      plate: 'KDL 462S',
      icon: '🔋',
      approval_status: 'approved',
      id_number: '20123458',
      services: ['battery', 'fuel', 'tire'],
    },
    // --- Wider metro area (Kiambu / Kajiado / Machakos) ---
    {
      name: 'Joseph Mwangi',
      business_name: 'Thika Highway Rescue',
      vehicle_type: 'Tow Truck',
      phone: '+254712000009',
      rating: 4.6,
      lat: -1.0333,
      lng: 37.0693,
      neighborhood: 'Thika',
      plate: 'KDN 118T',
      icon: '🚛',
      approval_status: 'approved',
      id_number: '21234569',
      services: ['towing', 'accident', 'engine'],
    },
    {
      name: 'Alice Wambui',
      business_name: 'Ruiru Auto Care',
      vehicle_type: 'Service Van',
      phone: '+254712000010',
      rating: 4.5,
      lat: -1.1500,
      lng: 36.9583,
      neighborhood: 'Ruiru',
      plate: 'KDP 224R',
      icon: '🔧',
      approval_status: 'approved',
      id_number: '22345670',
      services: ['tire', 'battery', 'engine'],
    },
    {
      name: 'Simon Kiplagat',
      business_name: 'Ngong Roadside Help',
      vehicle_type: 'Pickup + Tools',
      phone: '+254712000011',
      rating: 4.8,
      lat: -1.3667,
      lng: 36.6500,
      neighborhood: 'Ngong',
      plate: 'KDQ 331N',
      icon: '🔧',
      approval_status: 'approved',
      id_number: '23456781',
      services: ['tire', 'engine', 'battery', 'other'],
    },
    {
      name: 'Esther Nyambura',
      business_name: 'Rongai Rapid Response',
      vehicle_type: 'Response Motorbike',
      phone: '+254712000012',
      rating: 4.7,
      lat: -1.3959,
      lng: 36.7539,
      neighborhood: 'Rongai',
      plate: 'KDR 442R',
      icon: '🏍️',
      approval_status: 'approved',
      id_number: '24567892',
      services: ['tire', 'battery', 'fuel'],
    },
    {
      name: 'Daniel Mutiso',
      business_name: 'Kitengela Towing Services',
      vehicle_type: 'Flatbed Tow Truck',
      phone: '+254712000013',
      rating: 4.6,
      lat: -1.4740,
      lng: 36.9570,
      neighborhood: 'Kitengela',
      plate: 'KDS 553K',
      icon: '🚛',
      approval_status: 'approved',
      id_number: '25678903',
      services: ['towing', 'accident'],
    },
    {
      name: 'Grace Mueni',
      business_name: 'Machakos Motors Rescue',
      vehicle_type: 'Service Van',
      phone: '+254712000014',
      rating: 4.9,
      lat: -1.5177,
      lng: 37.2634,
      neighborhood: 'Machakos',
      plate: 'KDT 664M',
      icon: '🔧',
      approval_status: 'approved',
      id_number: '26789014',
      services: ['tire', 'engine', 'battery', 'fuel', 'other'],
    },
  ];

  for (const v of vendors) {
    const { services, ...vendorRow } = v;
    const [vendorId] = await knex('vendors').insert(vendorRow);
    await knex('vendor_services').insert(
      services.map((service_type) => ({ vendor_id: vendorId, service_type }))
    );
  }
};
